changelog:
  exclude:
    authors:
      - allcontributors
    labels:
      - ignore-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - "type: feature"
    - title: Bug Fixes 🐛
      labels:
        - "type: bug"
    - title: Documentation Changes
      labels:
        - "type: documentation"
    - title: Style and Structure Changes
      labels:
        - "type: refactor"
    - title: Other Changes
      labels:
        - "*"
