daysUntilStale: 365
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
  - "state: approved"
staleLabel: "state: inactive"
markComment: >
  This issue has been automatically marked as inactive because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
